language: java
jdk: oraclejdk8
os: linux
dist: trusty

env:
  - COVERAGE=0.35

script:
  - ./gradlew clean jar
  - ./gradlew test

after_success:
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv | xargs cat | awk -F',' '{print $3" "$4" "$5}'

before_deploy:
  - COVERAGE=$COVERAGE ./gradlew test jacocoTestCoverageVerification

deploy:
  - provider: script
    script: echo 'WIP'
    on:
      all_branches: true
