language: java
jdk:
  - oraclejdk8
  - oraclejdk9
os: linux
dist: trusty

script:
  - ./gradlew clean jar

jobs:
  include:
    - stage: test
      env:
        - COVERAGE=0.39
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/repository/order check
    - stage: test
      env:
        - COVERAGE=0.31
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/repository/user check

after_success:
  - find . -name jacocoTestReport.csv | xargs cat | awk -F',' '{print $3" "$4" "$5}'

deploy:
  - provider: script
    script: echo 'WIP'
    on:
      all_branches: true
