language: java
jdk: oraclejdk8
os: linux
dist: trusty

script:
  - ./gradlew clean jar

jobs:
  include:
  - stage: test
    env:
      - COVERAGE=0.5
     script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/ui check
  - stage: test
    env:
      - COVERAGE=0.5
    script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/service/cart check
  - stage: test
    env:
      - COVERAGE=0.5
    script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/service/user check
  - stage: test
    env:
      - COVERAGE=0.5
    script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/repository/order check
  - stage: test
    env:
      - COVERAGE=0.5
    script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/repository/cart check
  - stage: test
    env:
      - COVERAGE=0.5
    script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/repository/product check
  - stage: test
    env:
      - COVERAGE=0.5
    script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/repository/user check

after_success:
  - find . -name jacocoTestReport.csv | xargs cat | awk -F',' '{print $3" "$4" "$5}'

deploy:
  - provider: script
    script: echo 'WIP'
    on:
      all_branches: true
