language: java
os: linux
dist: trusty

jobs:
  include:
    - stage: build_jar
      jdk: oraclejdk8
      install: skip
      script: ./gradlew clean jar
    - stage: build_jar
      jdk: oraclejdk9
      install: skip
      script: ./gradlew clean jar
    - stage: test
      jdk: oraclejdk8
      env:
        - COVERAGE=0.5
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/ui check
    - stage: test
      jdk: oraclejdk8
      env:
        - COVERAGE=0.5
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/service/cart check
    - stage: test
      jdk: oraclejdk8
      env:
        - COVERAGE=0.5
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/service/user check
    - stage: test
      jdk: oraclejdk8
      env:
        - COVERAGE=0.39
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/repository/order check
    - stage: test
      jdk: oraclejdk8
      env:
        - COVERAGE=0.5
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/repository/cart check
    - stage: test
      jdk: oraclejdk8
      env:
        - COVERAGE=0.5
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/repository/product check
    - stage: test
      jdk: oraclejdk8
      env:
        - COVERAGE=0.31
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/repository/user check
    - stage: test
      jdk: oraclejdk9
      env:
        - COVERAGE=0.5
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/ui check
    - stage: test
      jdk: oraclejdk9
      env:
        - COVERAGE=0.5
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/service/cart check
    - stage: test
      jdk: oraclejdk9
      env:
        - COVERAGE=0.5
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/service/user check
    - stage: test
      jdk: oraclejdk9
      env:
        - COVERAGE=0.39
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/repository/order check
    - stage: test
      jdk: oraclejdk9
      env:
        - COVERAGE=0.5
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/repository/cart check
    - stage: test
      jdk: oraclejdk9
      env:
        - COVERAGE=0.5
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/repository/product check
    - stage: test
      jdk: oraclejdk9
      env:
        - COVERAGE=0.31
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/repository/user check

after_success:
  - find . -name jacocoTestReport.csv | xargs cat | awk -F',' '{print $3" "$4" "$5}'

deploy:
  - provider: script
    script: echo 'WIP'
    on:
      all_branches: true
