language: java
os: linux
dist: trusty

services:
  - docker

env:
  global:
    - secure: icge8AKkw1GulUB2rOx7mkXusKFBKGodsaRsdhAERbLZOs4Ku2C3WTKg9NCYMSBqX52Cr4GPac/iK9awvhbD8njV0uG/V9KzgeF0M0Y2m7G+VIX86J03rZXOw4yO6jDaB5wKn7Y2HlLvUYJrnWlZTStMk8nSN4ceXs8V65KEW0bnuuX93JQtHWCVEAWpqm2DnnOx1QGcFDtg5N932OE4lYQxhxGmcAPfUP8jb83yD7ADZKu+blKtiErZwT4AXUEMJz+fPQkh4R+CeET/JBiRxBhRYuFcUhNUKqE4hva/caTigR5TTrbNyeMnfRqlmE2Ua5o9lyraoRhw1MeXQvEFlvLS6BqL2fCvAO3toGDJ6bGxp+voj9DLouaoMSEgi7mlQlmorCXWuykZtDVYlArzJVTfhhOgoUSfKw9nrGZf51myftxR4jF1hvuXC+jyMZ7TiDmqZ5MJ/D8Rsk9mAzV9B7DEJ4/nevxcmeU5F7nPs120ipYCge1iWMFoJGUzNWzCwhgit5/8vJ23p//gXXBUZEoimwgyfGiEpHererg0cMsViIXTzXzTZA35YdS6thGVc/646s7uiEk2dk5QdCJ3AIOk0xEQUSXcow+sAYaWatIPn7So15Xrw561udSBtT0aopp7qFcK48etLWhun+Xufp8qj0bUb62hxFrNamKiG4A=
    - secure: jDNrgB6UJVudFA0iTh1hMH0KWLrNfygMsHvs02rnleGSvLdYYRsBGD2ViFIMiWDIX6NLMBtgNVGOCHKirlAh5r8xYDtXBpgw0UkSTUTB3rt531l/o7p6MiShzfZvgi0f0HiyqZnPAWODauur3v25sZ9UdtlAyztbH7Io4eZHaeS5LV4JQ/cPoMaHFA9z6pZdUgay/x0RQayZJogtEE1C7NRs+jnQmRhECQetAaNjOwZmEtVR7s9KSbQ/UqXlSpg8bIRf4i0Ux1Qsr5lpmT4dXeXts79AwGBgUadSM1LT5O2ofJ+y3g8eK+Pdt8JaepgdjgY/6QGdyuZkqp2TVCWnBZuqimXvkxKjYhGszpqgr4by3NDP3G19fXjKaZfvymEi5uknfnbsWhLQdJVyQkFbalCchy35fm3VV5ihx6AWUeUwabJ/HA5F84Igtf+cM8hZNLVndDpz8nxr9FjlaBW5p+MH4WI/XXzy2MToDDNZceTDyFbKIfXh84Lbr61xQCQPQO6YHVuJvyGGuNIVu0gJwzN3ZY2leEa7cXf0llk+KKvoPYECjLrB1KCcCif97dURvoB3Bl+SO4BhOW6pfG5nsvyZs0gB5OmMTNdC5HG8jdh9HnTT2QJIlGHz0fsg2Hj0zaM0dQngo9RiSccV6ffJ3VuDkFSOeysSXupFiDjCOds=

jobs:
  include:
    - stage: build_jar
      jdk: oraclejdk8
      install: skip
      script: ./gradlew clean jar
    - stage: build_jar
      jdk: oraclejdk9
      install: skip
      script: ./gradlew clean jar
    - stage: test
      jdk: oraclejdk8
      env:
        - COVERAGE=0.5
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/ui check
    - stage: test
      jdk: oraclejdk8
      env:
        - COVERAGE=0.5
        - BUILD_PATH=monolithic_ui
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/service/cart check
    - stage: test
      jdk: oraclejdk8
      env:
        - COVERAGE=0.5
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/service/user check
    - stage: test
      jdk: oraclejdk8
      env:
        - COVERAGE=0.36
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/repository/order check
    - stage: test
      jdk: oraclejdk8
      env:
        - COVERAGE=0.5
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/repository/cart check
    - stage: test
      jdk: oraclejdk8
      env:
        - COVERAGE=0.5
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/repository/product check
    - stage: test
      jdk: oraclejdk8
      env:
        - COVERAGE=0.31
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/repository/user check
    - stage: test
      jdk: oraclejdk9
      env:
        - COVERAGE=0.5
        - BUILD_PATH=monolithic_ui
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/ui check
    - stage: test
      jdk: oraclejdk9
      env:
        - COVERAGE=0.5
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/service/cart check
    - stage: test
      jdk: oraclejdk9
      env:
        - COVERAGE=0.5
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/service/user check
    - stage: test
      jdk: oraclejdk9
      env:
        - COVERAGE=0.36
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/repository/order check
    - stage: test
      jdk: oraclejdk9
      env:
        - COVERAGE=0.5
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/repository/cart check
    - stage: test
      jdk: oraclejdk9
      env:
        - COVERAGE=0.5
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/repository/product check
    - stage: test
      jdk: oraclejdk9
      env:
        - COVERAGE=0.31
      script: COVERAGE=${COVERAGE} ./gradlew -p ./monolithic/repository/user check

after_success:
  - find . -name jacocoTestReport.csv | xargs cat | awk -F',' '{print $3" "$4" "$5}'

before_deploy: ./gradlew -p ./monolithic/ui packageToContainer

deploy:
  - provider: script
    script: ./script/deploy.sh
    on:
      branch: master
    on:
      condition: "$BUILD_PATH=monolithic_ui"
